// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qz4mKtTsMEtOgimCymUEVKpuyl97AU8',
    appId: '1:55289791080:web:d218e65837efe7691931dd',
    messagingSenderId: '55289791080',
    projectId: 'calzadoskevin-83642',
    authDomain: 'calzadoskevin-83642.firebaseapp.com',
    storageBucket: 'calzadoskevin-83642.appspot.com',
    measurementId: 'G-SVKD25WC3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8NvvqmeP9bv_PX4DeO1mBjUe5xrTr8W8',
    appId: '1:55289791080:android:422aaf5978a9d5701931dd',
    messagingSenderId: '55289791080',
    projectId: 'calzadoskevin-83642',
    storageBucket: 'calzadoskevin-83642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUhQsdantgPNr8mX39f-qzvJ9zNSwine8',
    appId: '1:55289791080:ios:31d09b761ee5a4331931dd',
    messagingSenderId: '55289791080',
    projectId: 'calzadoskevin-83642',
    storageBucket: 'calzadoskevin-83642.appspot.com',
    iosClientId: '55289791080-5u1koalrna1shv13ljuspnp0r32lsqi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );
}
